# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testProjectAppysphere' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testProjectAppysphere
	 pod 'Alamofire', '~> 4.7'
	 pod 'SwiftEventBus'


  target 'testProjectAppysphereTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testProjectAppysphereUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
